# Generated by Django 5.1.4 on 2024-12-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyproduct', '0002_rename_store_name_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diyproduct.store'),
            preserve_default=False,
        ),
    ]
