# Generated by Django 5.1.4 on 2024-12-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyproduct', '0004_state_rename_name_purchaseorder_store_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
