# Generated by Django 5.1.4 on 2024-12-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyproduct', '0006_brands_store_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
