# Generated by Django 5.1.4 on 2024-12-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dblearning", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dblearning.store",
            ),
            preserve_default=False,
        ),
    ]
