# Generated by Django 5.1.4 on 2024-12-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dblearning', '0004_profile_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
