# Generated by Django 5.1.4 on 2024-12-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblearning', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dblearning.brand'),
        ),
    ]
